### ISSUE TITLE
Installation - error in sudo make: recipe for target 'fastx.o' failed

### ISSUE THREAD

**Issue by OndroV** [torognes/vsearch#454]
Hi, this error appeared when installing from source distribution. Is there anything I should do before running the final command (make install)?

```/usr/local/src/vsearch-2.17.1$ sudo make
make  all-recursive
make[1]: Entering directory '/usr/local/src/vsearch-2.17.1'
Making all in src
make[2]: Entering directory '/usr/local/src/vsearch-2.17.1/src'
g++ -DHAVE_CONFIG_H -I. -I..    -Wall -Wsign-compare -O3 -g -march=x86-64 -mtune=generic -msse2 -g -std=c++11 -MT libcpu_sse2_a-cpu.o -MD -MP -MF .deps/libcpu_sse2_a-cpu.Tpo -c -o libcpu_sse2_a-cpu.o `test -f 'cpu.cc' || echo './'`cpu.cc
mv -f .deps/libcpu_sse2_a-cpu.Tpo .deps/libcpu_sse2_a-cpu.Po
rm -f libcpu_sse2.a
ar cru libcpu_sse2.a libcpu_sse2_a-cpu.o  
ar: `u' modifier ignored since `D' is the default (see `U')
ranlib libcpu_sse2.a
...
...
g++ -DHAVE_CONFIG_H -I. -I..    -Wall -Wsign-compare -O3 -g -march=x86-64 -mtune=generic -g -std=c++11 -MT fastx.o -MD -MP -MF $depbase.Tpo -c -o fastx.o fastx.cc &&\
mv -f $depbase.Tpo $depbase.Po
fastx.cc: In function ‘uint64_t fastx_file_fill_buffer(fastx_handle)’:
fastx.cc:560:11: warning: variable ‘bytes_read’ set but not used [-Wunused-but-set-variable]
       int bytes_read = 0;
           ^~~~~~~~~~
fastx.cc:627:32: error: ‘bytes_read’ was not declared in this scope
       h->file_buffer.length += bytes_read;
                                ^~~~~~~~~~
fastx.cc:627:32: note: suggested alternative: ‘xopen_read’
       h->file_buffer.length += bytes_read;
                                ^~~~~~~~~~
                                xopen_read
fastx.cc: At global scope:
fastx.cc:630:1: error: expected declaration before ‘}’ token
 }
 ^
Makefile:697: recipe for target 'fastx.o' failed
make[2]: *** [fastx.o] Error 1
make[2]: Leaving directory '/usr/local/src/vsearch-2.17.1/src'
Makefile:377: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/usr/local/src/vsearch-2.17.1'
Makefile:318: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by frederic-mahe** [comment]
hi @OndroV I cannot replicate your bug, vsearch compiles correctly with every major GCC release (from 4.8 to 11.1). There was a small bug when compiling with GCC 4.8 and 4.9 but it is not related to your issue and it is fixed now (commit 683b8e509ff52acd62565fa68a699edb22624f80).

I am curious to know what version of GCC you are using, so please run:
```sh
# in the vsearch folder: 
gcc --version
make clean
git pull
./configure
make -j
```

**Comment by torognes** [comment]
Thanks for reporting this issue. There was an error in the code causing a compilation error when the zlib.h head file was unavailable. Fixed in commit f435de0c65a6426a765ba5a89de9f10958aed6f0.
